export const ProfileSectionFields = [
	{
		name: "fullname",
		type: "text",
		label: "Full Name",
		placeholder: "Enter full name",
		rules: { required: "Full Name is required" },
	},
	{
		name: "username",
		type: "text",
		label: "Username",
		placeholder: "Enter username",
		rules: { required: "Username is required" },
	},
	{
		name: "email",
		type: "email",
		label: "Email Address",
		placeholder: "example@domain.com",
		rules: {
			required: "Email is required",
			pattern: { value: /^\S+@\S+\.\S+$/, message: "Invalid email address" },
		},
	},
	{
		name: "phone",
		type: "tel",
		label: "Phone Number",
		placeholder: "Enter phone number",
		rules: {
			required: "Phone number should be 10 Digits",
			pattern: { value: /^[0-9]{10}$/, message: "Invalid phone number" },
		},
	},
	{
		name: "gender",
		type: "select",
		label: "Gender",
		placeholder: "Select gender",
		options: ["Male", "Female", "Other"],
		rules: { required: "Gender is required" },
	},
	{
		name: "dob",
		type: "date",
		label: "Date of Birth",
		placeholder: "YYYY-MM-DD",
		rules: { required: "Date of Birth is required" },
	},
	{
		name: "address",
		type: "text",
		label: "Address",
		placeholder: "Street, Apartment, City",
		rules: { required: "Address is required" },
	},
	{
		name: "pincode",
		type: "number",
		label: "Pincode",
		placeholder: "Enter 6-digit pincode",
		rules: {
			required: "Pincode should be 6 Digits",
			minLength: { value: 6, message: "Pincode must be 6 digits" },
			maxLength: { value: 6, message: "Pincode must be 6 digits" },
		},
	},
	{
		name: "state",
		type: "select",
		label: "State",
		placeholder: "Select state",
		options: [
			"Andhra Pradesh",
			"Arunachal Pradesh",
			"Assam",
			"Bihar",
			"Chhattisgarh",
			"Goa",
			"Gujarat",
			"Haryana",
			"Himachal Pradesh",
			"Jharkhand",
			"Karnataka",
			"Kerala",
			"Madhya Pradesh",
			"Maharashtra",
			"Manipur",
			"Meghalaya",
			"Mizoram",
			"Nagaland",
			"Odisha",
			"Punjab",
			"Rajasthan",
			"Sikkim",
			"Tamil Nadu",
			"Telangana",
			"Tripura",
			"Uttar Pradesh",
			"Uttarakhand",
			"West Bengal",
			"Delhi",
			"Jammu & Kashmir",
			"Ladakh",
			"Chandigarh",
			"Puducherry",
			"Andaman & Nicobar Islands",
			"Dadra & Nagar Haveli and Daman & Diu",
			"Lakshadweep",
		],
		rules: { required: "State is required" },
	},
];
